export { default as Home } from "./Home";
export { default as Layout } from "./Layout";
export { default as SlideControlButtons } from "./SlideControlButtons";
export { default as Cart } from "./Cart";
export { default as Collections } from "../pages/Collections";
export { default as Men } from "../pages/Men";
export { default as imageProduct1 } from "../assets/imageproduct1.jpg";
export { default as imageProduct2 } from "../assets/imageproduct2.jpg";
export { default as imageProduct3 } from "../assets/imageproduct3.jpg";
export { default as imageProduct4 } from "../assets/imageproduct4.jpg";
export { default as closeIcon } from "../assets/close.svg";
export { default as shoesCollection } from "../assets/shoes collection.jpg";
